package modele;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tblclient generated by hbm2java
 */
public class Tblclient implements java.io.Serializable {

	private BigDecimal idcli;
	private Tblusager tblusager;
	private String numcartecre;
	private String typecartecre;
	private BigDecimal moisexpcartedre;
	private BigDecimal anneeexpcartecre;

	public Tblclient() {
	}

	public Tblclient(BigDecimal idcli, Tblusager tblusager, String numcartecre, String typecartecre,
			BigDecimal moisexpcartedre, BigDecimal anneeexpcartecre) {
		this.idcli = idcli;
		this.tblusager = tblusager;
		this.numcartecre = numcartecre;
		this.typecartecre = typecartecre;
		this.moisexpcartedre = moisexpcartedre;
		this.anneeexpcartecre = anneeexpcartecre;
	}

	public BigDecimal getIdcli() {
		return this.idcli;
	}

	public void setIdcli(BigDecimal idcli) {
		this.idcli = idcli;
	}

	public Tblusager getTblusager() {
		return this.tblusager;
	}

	public void setTblusager(Tblusager tblusager) {
		this.tblusager = tblusager;
	}

	public String getNumcartecre() {
		return this.numcartecre;
	}

	public void setNumcartecre(String numcartecre) {
		this.numcartecre = numcartecre;
	}

	public String getTypecartecre() {
		return this.typecartecre;
	}

	public void setTypecartecre(String typecartecre) {
		this.typecartecre = typecartecre;
	}

	public BigDecimal getMoisexpcartedre() {
		return this.moisexpcartedre;
	}

	public void setMoisexpcartedre(BigDecimal moisexpcartedre) {
		this.moisexpcartedre = moisexpcartedre;
	}

	public BigDecimal getAnneeexpcartecre() {
		return this.anneeexpcartecre;
	}

	public void setAnneeexpcartecre(BigDecimal anneeexpcartecre) {
		this.anneeexpcartecre = anneeexpcartecre;
	}

}
