package modele;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tblcopie generated by hbm2java
 */
public class Tblcopie implements java.io.Serializable {

	private String noseriecopie;
	private Tblfilm tblfilm;
	private char etatcopie;
	private Set tbllocations = new HashSet(0);

	public Tblcopie() {
	}

	public Tblcopie(String noseriecopie, Tblfilm tblfilm, char etatcopie) {
		this.noseriecopie = noseriecopie;
		this.tblfilm = tblfilm;
		this.etatcopie = etatcopie;
	}

	public Tblcopie(String noseriecopie, Tblfilm tblfilm, char etatcopie, Set tbllocations) {
		this.noseriecopie = noseriecopie;
		this.tblfilm = tblfilm;
		this.etatcopie = etatcopie;
		this.tbllocations = tbllocations;
	}

	public String getNoseriecopie() {
		return this.noseriecopie;
	}

	public void setNoseriecopie(String noseriecopie) {
		this.noseriecopie = noseriecopie;
	}

	public Tblfilm getTblfilm() {
		return this.tblfilm;
	}

	public void setTblfilm(Tblfilm tblfilm) {
		this.tblfilm = tblfilm;
	}

	public char getEtatcopie() {
		return this.etatcopie;
	}

	public void setEtatcopie(char etatcopie) {
		this.etatcopie = etatcopie;
	}

	public Set getTbllocations() {
		return this.tbllocations;
	}

	public void setTbllocations(Set tbllocations) {
		this.tbllocations = tbllocations;
	}

}
