package modele;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TblroleId generated by hbm2java
 */
public class TblroleId implements java.io.Serializable {

	private BigDecimal idfilm;
	private BigDecimal idacteur;
	private BigDecimal idperso;

	public TblroleId() {
	}

	public TblroleId(BigDecimal idfilm, BigDecimal idacteur, BigDecimal idperso) {
		this.idfilm = idfilm;
		this.idacteur = idacteur;
		this.idperso = idperso;
	}

	public BigDecimal getIdfilm() {
		return this.idfilm;
	}

	public void setIdfilm(BigDecimal idfilm) {
		this.idfilm = idfilm;
	}

	public BigDecimal getIdacteur() {
		return this.idacteur;
	}

	public void setIdacteur(BigDecimal idacteur) {
		this.idacteur = idacteur;
	}

	public BigDecimal getIdperso() {
		return this.idperso;
	}

	public void setIdperso(BigDecimal idperso) {
		this.idperso = idperso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblroleId))
			return false;
		TblroleId castOther = (TblroleId) other;

		return ((this.getIdfilm() == castOther.getIdfilm()) || (this.getIdfilm() != null
				&& castOther.getIdfilm() != null && this.getIdfilm().equals(castOther.getIdfilm())))
				&& ((this.getIdacteur() == castOther.getIdacteur()) || (this.getIdacteur() != null
						&& castOther.getIdacteur() != null && this.getIdacteur().equals(castOther.getIdacteur())))
				&& ((this.getIdperso() == castOther.getIdperso()) || (this.getIdperso() != null
						&& castOther.getIdperso() != null && this.getIdperso().equals(castOther.getIdperso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdfilm() == null ? 0 : this.getIdfilm().hashCode());
		result = 37 * result + (getIdacteur() == null ? 0 : this.getIdacteur().hashCode());
		result = 37 * result + (getIdperso() == null ? 0 : this.getIdperso().hashCode());
		return result;
	}

}
