package modele;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblusager generated by hbm2java
 */
public class Tblusager implements java.io.Serializable {

	private String courrielusag;
	private Tblforfait tblforfait;
	private String nomusag;
	private String prenomusag;
	private String notelusag;
	private BigDecimal nociviqueusag;
	private String rueusag;
	private String villeusag;
	private String provinceusag;
	private String codeposusag;
	private Date datenaissusag;
	private String passusag;
	private Set tblemployes = new HashSet(0);
	private Set tbllocations = new HashSet(0);
	private Set tblclients = new HashSet(0);

	public Tblusager() {
	}

	public Tblusager(String courrielusag, String nomusag, String prenomusag, String notelusag, BigDecimal nociviqueusag,
			String rueusag, String villeusag, String provinceusag, String codeposusag, Date datenaissusag,
			String passusag) {
		this.courrielusag = courrielusag;
		this.nomusag = nomusag;
		this.prenomusag = prenomusag;
		this.notelusag = notelusag;
		this.nociviqueusag = nociviqueusag;
		this.rueusag = rueusag;
		this.villeusag = villeusag;
		this.provinceusag = provinceusag;
		this.codeposusag = codeposusag;
		this.datenaissusag = datenaissusag;
		this.passusag = passusag;
	}

	public Tblusager(String courrielusag, Tblforfait tblforfait, String nomusag, String prenomusag, String notelusag,
			BigDecimal nociviqueusag, String rueusag, String villeusag, String provinceusag, String codeposusag,
			Date datenaissusag, String passusag, Set tblemployes, Set tbllocations, Set tblclients) {
		this.courrielusag = courrielusag;
		this.tblforfait = tblforfait;
		this.nomusag = nomusag;
		this.prenomusag = prenomusag;
		this.notelusag = notelusag;
		this.nociviqueusag = nociviqueusag;
		this.rueusag = rueusag;
		this.villeusag = villeusag;
		this.provinceusag = provinceusag;
		this.codeposusag = codeposusag;
		this.datenaissusag = datenaissusag;
		this.passusag = passusag;
		this.tblemployes = tblemployes;
		this.tbllocations = tbllocations;
		this.tblclients = tblclients;
	}

	public String getCourrielusag() {
		return this.courrielusag;
	}

	public void setCourrielusag(String courrielusag) {
		this.courrielusag = courrielusag;
	}

	public Tblforfait getTblforfait() {
		return this.tblforfait;
	}

	public void setTblforfait(Tblforfait tblforfait) {
		this.tblforfait = tblforfait;
	}

	public String getNomusag() {
		return this.nomusag;
	}

	public void setNomusag(String nomusag) {
		this.nomusag = nomusag;
	}

	public String getPrenomusag() {
		return this.prenomusag;
	}

	public void setPrenomusag(String prenomusag) {
		this.prenomusag = prenomusag;
	}

	public String getNotelusag() {
		return this.notelusag;
	}

	public void setNotelusag(String notelusag) {
		this.notelusag = notelusag;
	}

	public BigDecimal getNociviqueusag() {
		return this.nociviqueusag;
	}

	public void setNociviqueusag(BigDecimal nociviqueusag) {
		this.nociviqueusag = nociviqueusag;
	}

	public String getRueusag() {
		return this.rueusag;
	}

	public void setRueusag(String rueusag) {
		this.rueusag = rueusag;
	}

	public String getVilleusag() {
		return this.villeusag;
	}

	public void setVilleusag(String villeusag) {
		this.villeusag = villeusag;
	}

	public String getProvinceusag() {
		return this.provinceusag;
	}

	public void setProvinceusag(String provinceusag) {
		this.provinceusag = provinceusag;
	}

	public String getCodeposusag() {
		return this.codeposusag;
	}

	public void setCodeposusag(String codeposusag) {
		this.codeposusag = codeposusag;
	}

	public Date getDatenaissusag() {
		return this.datenaissusag;
	}

	public void setDatenaissusag(Date datenaissusag) {
		this.datenaissusag = datenaissusag;
	}

	public String getPassusag() {
		return this.passusag;
	}

	public void setPassusag(String passusag) {
		this.passusag = passusag;
	}

	public Set getTblemployes() {
		return this.tblemployes;
	}

	public void setTblemployes(Set tblemployes) {
		this.tblemployes = tblemployes;
	}

	public Set getTbllocations() {
		return this.tbllocations;
	}

	public void setTbllocations(Set tbllocations) {
		this.tbllocations = tbllocations;
	}

	public Set getTblclients() {
		return this.tblclients;
	}

	public void setTblclients(Set tblclients) {
		this.tblclients = tblclients;
	}

}
