package modele;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

/**
 * VwAfficheclient generated by hbm2java
 */
public class VwAfficheclient implements java.io.Serializable {

	private VwAfficheclientId id;

	public VwAfficheclient() {
	}

	public VwAfficheclient(VwAfficheclientId id) {
		this.id = id;
	}

	public VwAfficheclientId getId() {
		return this.id;
	}

	public void setId(VwAfficheclientId id) {
		this.id = id;
	}

}
