package modele.hibernate;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblacteur generated by hbm2java
 */
public class Tblacteur implements java.io.Serializable {

	private BigDecimal idacteur;
	private String nomacteur;
	private String prenacteur;
	private Date datenaissacteur;
	private String lieunaissacteur;
	private String bioacteur;
	private Set tblroles = new HashSet(0);

	public Tblacteur() {
	}

	public Tblacteur(BigDecimal idacteur, String nomacteur, String prenacteur) {
		this.idacteur = idacteur;
		this.nomacteur = nomacteur;
		this.prenacteur = prenacteur;
	}

	public Tblacteur(BigDecimal idacteur, String nomacteur, String prenacteur, Date datenaissacteur,
			String lieunaissacteur, String bioacteur, Set tblroles) {
		this.idacteur = idacteur;
		this.nomacteur = nomacteur;
		this.prenacteur = prenacteur;
		this.datenaissacteur = datenaissacteur;
		this.lieunaissacteur = lieunaissacteur;
		this.bioacteur = bioacteur;
		this.tblroles = tblroles;
	}

	public BigDecimal getIdacteur() {
		return this.idacteur;
	}

	public void setIdacteur(BigDecimal idacteur) {
		this.idacteur = idacteur;
	}

	public String getNomacteur() {
		return this.nomacteur;
	}

	public void setNomacteur(String nomacteur) {
		this.nomacteur = nomacteur;
	}

	public String getPrenacteur() {
		return this.prenacteur;
	}

	public void setPrenacteur(String prenacteur) {
		this.prenacteur = prenacteur;
	}

	public Date getDatenaissacteur() {
		return this.datenaissacteur;
	}

	public void setDatenaissacteur(Date datenaissacteur) {
		this.datenaissacteur = datenaissacteur;
	}

	public String getLieunaissacteur() {
		return this.lieunaissacteur;
	}

	public void setLieunaissacteur(String lieunaissacteur) {
		this.lieunaissacteur = lieunaissacteur;
	}

	public String getBioacteur() {
		return this.bioacteur;
	}

	public void setBioacteur(String bioacteur) {
		this.bioacteur = bioacteur;
	}

	public Set getTblroles() {
		return this.tblroles;
	}

	public void setTblroles(Set tblroles) {
		this.tblroles = tblroles;
	}

}
