package modele.hibernate;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Tblemploye generated by hbm2java
 */
public class Tblemploye implements java.io.Serializable {

	private BigDecimal matriculeemp;
	private Tblusager tblusager;

	public Tblemploye() {
	}

	public Tblemploye(BigDecimal matriculeemp, Tblusager tblusager) {
		this.matriculeemp = matriculeemp;
		this.tblusager = tblusager;
	}

	public BigDecimal getMatriculeemp() {
		return this.matriculeemp;
	}

	public void setMatriculeemp(BigDecimal matriculeemp) {
		this.matriculeemp = matriculeemp;
	}

	public Tblusager getTblusager() {
		return this.tblusager;
	}

	public void setTblusager(Tblusager tblusager) {
		this.tblusager = tblusager;
	}

}
