package modele.hibernate;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tblgenre generated by hbm2java
 */
public class Tblgenre implements java.io.Serializable {

	private String nomgenre;
	private Set tblfilms = new HashSet(0);

	public Tblgenre() {
	}

	public Tblgenre(String nomgenre) {
		this.nomgenre = nomgenre;
	}

	public Tblgenre(String nomgenre, Set tblfilms) {
		this.nomgenre = nomgenre;
		this.tblfilms = tblfilms;
	}

	public String getNomgenre() {
		return this.nomgenre;
	}

	public void setNomgenre(String nomgenre) {
		this.nomgenre = nomgenre;
	}

	public Set getTblfilms() {
		return this.tblfilms;
	}

	public void setTblfilms(Set tblfilms) {
		this.tblfilms = tblfilms;
	}

}
