package modele.hibernate;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblpersonnage generated by hbm2java
 */
public class Tblpersonnage implements java.io.Serializable {

	private BigDecimal idperso;
	private String nomperso;
	private Set tblroles = new HashSet(0);

	public Tblpersonnage() {
	}

	public Tblpersonnage(BigDecimal idperso, String nomperso) {
		this.idperso = idperso;
		this.nomperso = nomperso;
	}

	public Tblpersonnage(BigDecimal idperso, String nomperso, Set tblroles) {
		this.idperso = idperso;
		this.nomperso = nomperso;
		this.tblroles = tblroles;
	}

	public BigDecimal getIdperso() {
		return this.idperso;
	}

	public void setIdperso(BigDecimal idperso) {
		this.idperso = idperso;
	}

	public String getNomperso() {
		return this.nomperso;
	}

	public void setNomperso(String nomperso) {
		this.nomperso = nomperso;
	}

	public Set getTblroles() {
		return this.tblroles;
	}

	public void setTblroles(Set tblroles) {
		this.tblroles = tblroles;
	}

}
