package modele.hibernate;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

/**
 * Tblrole generated by hbm2java
 */
public class Tblrole implements java.io.Serializable {

	private TblroleId id;
	private Tblpersonnage tblpersonnage;
	private Tblfilm tblfilm;
	private Tblacteur tblacteur;

	public Tblrole() {
	}

	public Tblrole(TblroleId id, Tblpersonnage tblpersonnage, Tblfilm tblfilm, Tblacteur tblacteur) {
		this.id = id;
		this.tblpersonnage = tblpersonnage;
		this.tblfilm = tblfilm;
		this.tblacteur = tblacteur;
	}

	public TblroleId getId() {
		return this.id;
	}

	public void setId(TblroleId id) {
		this.id = id;
	}

	public Tblpersonnage getTblpersonnage() {
		return this.tblpersonnage;
	}

	public void setTblpersonnage(Tblpersonnage tblpersonnage) {
		this.tblpersonnage = tblpersonnage;
	}

	public Tblfilm getTblfilm() {
		return this.tblfilm;
	}

	public void setTblfilm(Tblfilm tblfilm) {
		this.tblfilm = tblfilm;
	}

	public Tblacteur getTblacteur() {
		return this.tblacteur;
	}

	public void setTblacteur(Tblacteur tblacteur) {
		this.tblacteur = tblacteur;
	}

}
