package modele.hibernate;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblscenariste generated by hbm2java
 */
public class Tblscenariste implements java.io.Serializable {

	private BigDecimal idscen;
	private String nomscen;
	private String prenscen;
	private Set tblfilms = new HashSet(0);

	public Tblscenariste() {
	}

	public Tblscenariste(BigDecimal idscen, String nomscen, String prenscen) {
		this.idscen = idscen;
		this.nomscen = nomscen;
		this.prenscen = prenscen;
	}

	public Tblscenariste(BigDecimal idscen, String nomscen, String prenscen, Set tblfilms) {
		this.idscen = idscen;
		this.nomscen = nomscen;
		this.prenscen = prenscen;
		this.tblfilms = tblfilms;
	}

	public BigDecimal getIdscen() {
		return this.idscen;
	}

	public void setIdscen(BigDecimal idscen) {
		this.idscen = idscen;
	}

	public String getNomscen() {
		return this.nomscen;
	}

	public void setNomscen(String nomscen) {
		this.nomscen = nomscen;
	}

	public String getPrenscen() {
		return this.prenscen;
	}

	public void setPrenscen(String prenscen) {
		this.prenscen = prenscen;
	}

	public Set getTblfilms() {
		return this.tblfilms;
	}

	public void setTblfilms(Set tblfilms) {
		this.tblfilms = tblfilms;
	}

}
