package modele.hibernate;
// Generated 2015-11-15 12:00:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * VwAfficheclientId generated by hbm2java
 */
public class VwAfficheclientId implements java.io.Serializable {

	private BigDecimal idcli;
	private String numcartecre;
	private String typecartecre;
	private BigDecimal moisexpcartedre;
	private BigDecimal anneeexpcartecre;
	private String courrielusag;
	private String nomusag;
	private String prenomusag;
	private String notelusag;
	private BigDecimal nociviqueusag;
	private String rueusag;
	private String villeusag;
	private String provinceusag;
	private String codeposusag;
	private Date datenaissusag;
	private String nomforfait;

	public VwAfficheclientId() {
	}

	public VwAfficheclientId(BigDecimal idcli, String numcartecre, String typecartecre, BigDecimal moisexpcartedre,
			BigDecimal anneeexpcartecre, String courrielusag, String nomusag, String prenomusag, String notelusag,
			BigDecimal nociviqueusag, String rueusag, String villeusag, String provinceusag, String codeposusag,
			Date datenaissusag) {
		this.idcli = idcli;
		this.numcartecre = numcartecre;
		this.typecartecre = typecartecre;
		this.moisexpcartedre = moisexpcartedre;
		this.anneeexpcartecre = anneeexpcartecre;
		this.courrielusag = courrielusag;
		this.nomusag = nomusag;
		this.prenomusag = prenomusag;
		this.notelusag = notelusag;
		this.nociviqueusag = nociviqueusag;
		this.rueusag = rueusag;
		this.villeusag = villeusag;
		this.provinceusag = provinceusag;
		this.codeposusag = codeposusag;
		this.datenaissusag = datenaissusag;
	}

	public VwAfficheclientId(BigDecimal idcli, String numcartecre, String typecartecre, BigDecimal moisexpcartedre,
			BigDecimal anneeexpcartecre, String courrielusag, String nomusag, String prenomusag, String notelusag,
			BigDecimal nociviqueusag, String rueusag, String villeusag, String provinceusag, String codeposusag,
			Date datenaissusag, String nomforfait) {
		this.idcli = idcli;
		this.numcartecre = numcartecre;
		this.typecartecre = typecartecre;
		this.moisexpcartedre = moisexpcartedre;
		this.anneeexpcartecre = anneeexpcartecre;
		this.courrielusag = courrielusag;
		this.nomusag = nomusag;
		this.prenomusag = prenomusag;
		this.notelusag = notelusag;
		this.nociviqueusag = nociviqueusag;
		this.rueusag = rueusag;
		this.villeusag = villeusag;
		this.provinceusag = provinceusag;
		this.codeposusag = codeposusag;
		this.datenaissusag = datenaissusag;
		this.nomforfait = nomforfait;
	}

	public BigDecimal getIdcli() {
		return this.idcli;
	}

	public void setIdcli(BigDecimal idcli) {
		this.idcli = idcli;
	}

	public String getNumcartecre() {
		return this.numcartecre;
	}

	public void setNumcartecre(String numcartecre) {
		this.numcartecre = numcartecre;
	}

	public String getTypecartecre() {
		return this.typecartecre;
	}

	public void setTypecartecre(String typecartecre) {
		this.typecartecre = typecartecre;
	}

	public BigDecimal getMoisexpcartedre() {
		return this.moisexpcartedre;
	}

	public void setMoisexpcartedre(BigDecimal moisexpcartedre) {
		this.moisexpcartedre = moisexpcartedre;
	}

	public BigDecimal getAnneeexpcartecre() {
		return this.anneeexpcartecre;
	}

	public void setAnneeexpcartecre(BigDecimal anneeexpcartecre) {
		this.anneeexpcartecre = anneeexpcartecre;
	}

	public String getCourrielusag() {
		return this.courrielusag;
	}

	public void setCourrielusag(String courrielusag) {
		this.courrielusag = courrielusag;
	}

	public String getNomusag() {
		return this.nomusag;
	}

	public void setNomusag(String nomusag) {
		this.nomusag = nomusag;
	}

	public String getPrenomusag() {
		return this.prenomusag;
	}

	public void setPrenomusag(String prenomusag) {
		this.prenomusag = prenomusag;
	}

	public String getNotelusag() {
		return this.notelusag;
	}

	public void setNotelusag(String notelusag) {
		this.notelusag = notelusag;
	}

	public BigDecimal getNociviqueusag() {
		return this.nociviqueusag;
	}

	public void setNociviqueusag(BigDecimal nociviqueusag) {
		this.nociviqueusag = nociviqueusag;
	}

	public String getRueusag() {
		return this.rueusag;
	}

	public void setRueusag(String rueusag) {
		this.rueusag = rueusag;
	}

	public String getVilleusag() {
		return this.villeusag;
	}

	public void setVilleusag(String villeusag) {
		this.villeusag = villeusag;
	}

	public String getProvinceusag() {
		return this.provinceusag;
	}

	public void setProvinceusag(String provinceusag) {
		this.provinceusag = provinceusag;
	}

	public String getCodeposusag() {
		return this.codeposusag;
	}

	public void setCodeposusag(String codeposusag) {
		this.codeposusag = codeposusag;
	}

	public Date getDatenaissusag() {
		return this.datenaissusag;
	}

	public void setDatenaissusag(Date datenaissusag) {
		this.datenaissusag = datenaissusag;
	}

	public String getNomforfait() {
		return this.nomforfait;
	}

	public void setNomforfait(String nomforfait) {
		this.nomforfait = nomforfait;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwAfficheclientId))
			return false;
		VwAfficheclientId castOther = (VwAfficheclientId) other;

		return ((this.getIdcli() == castOther.getIdcli()) || (this.getIdcli() != null && castOther.getIdcli() != null
				&& this.getIdcli().equals(castOther.getIdcli())))
				&& ((this.getNumcartecre() == castOther.getNumcartecre())
						|| (this.getNumcartecre() != null && castOther.getNumcartecre() != null
								&& this.getNumcartecre().equals(castOther.getNumcartecre())))
				&& ((this.getTypecartecre() == castOther.getTypecartecre())
						|| (this.getTypecartecre() != null && castOther.getTypecartecre() != null
								&& this.getTypecartecre().equals(castOther.getTypecartecre())))
				&& ((this.getMoisexpcartedre() == castOther.getMoisexpcartedre())
						|| (this.getMoisexpcartedre() != null && castOther.getMoisexpcartedre() != null
								&& this.getMoisexpcartedre().equals(castOther.getMoisexpcartedre())))
				&& ((this.getAnneeexpcartecre() == castOther.getAnneeexpcartecre())
						|| (this.getAnneeexpcartecre() != null && castOther.getAnneeexpcartecre() != null
								&& this.getAnneeexpcartecre().equals(castOther.getAnneeexpcartecre())))
				&& ((this.getCourrielusag() == castOther.getCourrielusag())
						|| (this.getCourrielusag() != null && castOther.getCourrielusag() != null
								&& this.getCourrielusag().equals(castOther.getCourrielusag())))
				&& ((this.getNomusag() == castOther.getNomusag()) || (this.getNomusag() != null
						&& castOther.getNomusag() != null && this.getNomusag().equals(castOther.getNomusag())))
				&& ((this.getPrenomusag() == castOther.getPrenomusag()) || (this.getPrenomusag() != null
						&& castOther.getPrenomusag() != null && this.getPrenomusag().equals(castOther.getPrenomusag())))
				&& ((this.getNotelusag() == castOther.getNotelusag()) || (this.getNotelusag() != null
						&& castOther.getNotelusag() != null && this.getNotelusag().equals(castOther.getNotelusag())))
				&& ((this.getNociviqueusag() == castOther.getNociviqueusag())
						|| (this.getNociviqueusag() != null && castOther.getNociviqueusag() != null
								&& this.getNociviqueusag().equals(castOther.getNociviqueusag())))
				&& ((this.getRueusag() == castOther.getRueusag()) || (this.getRueusag() != null
						&& castOther.getRueusag() != null && this.getRueusag().equals(castOther.getRueusag())))
				&& ((this.getVilleusag() == castOther.getVilleusag()) || (this.getVilleusag() != null
						&& castOther.getVilleusag() != null && this.getVilleusag().equals(castOther.getVilleusag())))
				&& ((this.getProvinceusag() == castOther.getProvinceusag())
						|| (this.getProvinceusag() != null && castOther.getProvinceusag() != null
								&& this.getProvinceusag().equals(castOther.getProvinceusag())))
				&& ((this.getCodeposusag() == castOther.getCodeposusag())
						|| (this.getCodeposusag() != null && castOther.getCodeposusag() != null
								&& this.getCodeposusag().equals(castOther.getCodeposusag())))
				&& ((this.getDatenaissusag() == castOther.getDatenaissusag())
						|| (this.getDatenaissusag() != null && castOther.getDatenaissusag() != null
								&& this.getDatenaissusag().equals(castOther.getDatenaissusag())))
				&& ((this.getNomforfait() == castOther.getNomforfait())
						|| (this.getNomforfait() != null && castOther.getNomforfait() != null
								&& this.getNomforfait().equals(castOther.getNomforfait())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdcli() == null ? 0 : this.getIdcli().hashCode());
		result = 37 * result + (getNumcartecre() == null ? 0 : this.getNumcartecre().hashCode());
		result = 37 * result + (getTypecartecre() == null ? 0 : this.getTypecartecre().hashCode());
		result = 37 * result + (getMoisexpcartedre() == null ? 0 : this.getMoisexpcartedre().hashCode());
		result = 37 * result + (getAnneeexpcartecre() == null ? 0 : this.getAnneeexpcartecre().hashCode());
		result = 37 * result + (getCourrielusag() == null ? 0 : this.getCourrielusag().hashCode());
		result = 37 * result + (getNomusag() == null ? 0 : this.getNomusag().hashCode());
		result = 37 * result + (getPrenomusag() == null ? 0 : this.getPrenomusag().hashCode());
		result = 37 * result + (getNotelusag() == null ? 0 : this.getNotelusag().hashCode());
		result = 37 * result + (getNociviqueusag() == null ? 0 : this.getNociviqueusag().hashCode());
		result = 37 * result + (getRueusag() == null ? 0 : this.getRueusag().hashCode());
		result = 37 * result + (getVilleusag() == null ? 0 : this.getVilleusag().hashCode());
		result = 37 * result + (getProvinceusag() == null ? 0 : this.getProvinceusag().hashCode());
		result = 37 * result + (getCodeposusag() == null ? 0 : this.getCodeposusag().hashCode());
		result = 37 * result + (getDatenaissusag() == null ? 0 : this.getDatenaissusag().hashCode());
		result = 37 * result + (getNomforfait() == null ? 0 : this.getNomforfait().hashCode());
		return result;
	}

}
